# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fdabd467e24ab6453d51d95652f56e5ff03cd9c78ed9167e4281f0f178c820f42c25323013a7b7c0900736c0262006004ec443e9b7f8bcb4a0a5096a3b4c062

test:
  secret_key_base: ea7669b7181d326e0ed9a279e4e039b2ec71f9725408e558aa5884f4158ef324e2737805e00b8a77d3b432edaa72cdb1fbc275a475df6f0f60356d5fc3c9995b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
